# Generated by Django 6.0.5 on 2026-05-22 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_created=True)),
                ('content', models.TextField()),
                ('reaction', models.CharField(blank=True, choices=[('😂', 'Laugh'), ('😭', 'Cry'), ('🎉', 'Celebrate'), ('👀', 'Eyes'), ('😎', 'Cool'), ('😘', 'Kiss'), ('❤', 'Heart')], max_length=10, null=True)),
                ('username', models.CharField(max_length=255)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.room')),
            ],
        ),
    ]
