# Generated by Django 6.0.5 on 2026-05-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_messages_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
